### ISSUE TITLE
Keybindings don't work well with Ubuntu (Unity)

### ISSUE THREAD

**Issue by pradyunsg** [svenfraeys/SublimeFoldPython#1]
First Issue! Yay!

Some key bindings, namely <kbd>Ctrl+Shift+Arrow</kbd> don't work well with Ubuntu workspaces. You might want to change that to something along the lines <kbd>Ctrl+k</kbd> + <kbd>Ctrl+key</kbd>.

**Comment by svenfraeys** [comment]
hey,

ah did not knew that you could hook it up to a command like this.
mainly tested my tool on Windows. And testing on linux gave indeed more problems.

I'll give it a try to adapt it to just keeping the main key but with the ctrl + K thing like you suggest

**Comment by svenfraeys** [comment]
hello,
I made changes and added shortcuts that you suggested. (i still kept the original shortcuts for the moment)

Only thing I have my doubts is that it is difficult to navigate easely if you do the "arrow down/up" actions; Since you want to do these actions fast after eachother to navigate.

Can you let me know if these work better ?
thanks again for reporting ! motivates to improve it :)

**Comment by pradyunsg** [comment]
Trying it now.. Also I another reason I failed to mention was [this](http://sublime-text-unofficial-documentation.readthedocs.org/en/sublime-text-3/reference/key_bindings.html#warning-about-bindable-keys).

And just in case you didn't know, that site is a  great resource.

**Comment by bismarckjunior** [comment]
@svenfraeys ,

The key bindings are not working on  my end, none of the shortcuts work ( neither [Crtrl + k]), been trying to get it working for about an hour. Running latest Sublime version 2 for Windows Vista.

**Comment by pradyunsg** [comment]
@bismarckjunior Is that still a problem? (Editted)

**Comment by pradyun** [comment]
Offtopic: You might want to start using Github releases (tag releases with semantic versioning). Makes life easier with Package Control as well...

**Comment by pradyunsg** [comment]
Bump. It's resolved for me as far as I remember.

I just got an idea, why not have different shortcuts for Windows + OSX, Linux? As in the Ctrl+K shortcuts for Linux users and the <kbd><kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>...</kbd></kbd> for OSX and Windows.

**Comment by pradyunsg** [comment]
Whoops! Closed by mistake.

**Comment by pradyunsg** [comment]
Is simply <kbd><kbd>Alt</kbd>+<kbd>Arrow</kbd></kbd> fine?

**Comment by pradyunsg** [comment]
Closing because it got fixed and I'm happy with my workflow now.

Thanks!

**Comment by bismarckjunior** [comment]
I'm ok with Ubuntu, my problem now is Windows. Key bindings like comment (Ctrl + /) does not work, I need to use Ctrl+;. I think the problem is key map, when I use console to see key map, Ctrl+; is Ctrl+/. My keyboard is ABNT.

**Comment by bismarckjunior** [comment]
Is there any issue open about it?
